name: demos
include:
  - ./services/web-server/nginx/docker-compose.yml
  - ./services/lazy-manager/docker-compose.yml
  - ./services/python/python-go-test/docker-compose.yml
  - ./services/go/go-worker/docker-compose.yml
  - ./services/deno/code-executor/docker-compose.yml
  - ./services/deno/deno-test/docker-compose.yml
