services:
  python-app:
    build: ./services/python/python-app
    ports:
      - "8000:8000" # Expose for Caddy to proxy, or for direct local testing
    environment:
      # These variables allow python-app to find the other services
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      GO_WORKER_URL: ${GO_WORKER_URL}
    depends_on:
      - db
      - go-worker
    restart: on-failure

  go-worker:
    build: ./services/go/go-worker
    expose:
      - "8080" # Only expose internally to the Docker network
    restart: on-failure

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  deno-app:
    build: ./services/deno/deno-app
    expose:
      - "8000"
    restart: on-failure

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./services/static/frontend/public:/var/www/html
      - ./services/static/another-frontend/public:/var/www/another-html
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - python-app

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
