services:
  instant-graph-maker:
    image: ghcr.io/pnettto/instant-graph-maker:latest
    build:
      context: .
    profiles:
      - lazy
    labels:
      - remove_after_use
    expose:
      - "8000"
    restart: on-failure