services:
  parallelism-main:
    build: ./main
    profiles:
      - lazy
    labels:
      - remove_after_use
    expose:
      - "8000"
    environment:
      DB_HOST: parallelism-db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - parallelism-worker
      - parallelism-db
    restart: on-failure

  parallelism-worker:
    build: ./worker
    profiles:
      - lazy
    expose:
      - "8000"
    restart: on-failure

  parallelism-db:
    image: postgres:17-alpine
    profiles:
      - lazy
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - parallelism-postgres:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  parallelism-postgres:
