name: demo-garden
include:
  - ./services/code-executor/docker-compose.yml
  - ./services/deno-test/docker-compose.yml
  - ./services/lazy-loader/docker-compose.yml
  - ./services/nginx/docker-compose.yml
  - ./services/parallelism/docker-compose.yml
  - ./services/spotify-api/docker-compose.yml
